name: cactus_example
description: Example app for the `cactus` library.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cactus:
    path: ../
  read_pdf_text: ^0.3.1
  file_picker: ^8.1.2
  solar_icons: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
