name: cactus_example
description: Example app for the `cactus` library.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cactus:
    path: ../
  read_pdf_text: ^0.3.1
  file_picker: ^10.3.3
  shared_preferences: ^2.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
