name: cactus
description: "Framework for running AI models on mobile devices"
version: 0.2.7
homepage: https://cactuscompute.com
repository: https://github.com/cactus-compute/cactus

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  http: ^1.2.1 
  path_provider: ^2.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  crypto: ^3.0.1
  uuid: ^4.0.0
  intl: ^0.18.0
  flutter_js: ^0.8.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true